/// <reference types="webgl2" />
export interface CanvasMock {
    width: number;
    height: number;
    clientWidth: number;
    clientHeight: number;
}
export declare class WebGL2RenderingContextMock implements WebGL2RenderingContext {
    readonly ACTIVE_ATTRIBUTES: number;
    readonly ACTIVE_TEXTURE: number;
    readonly ACTIVE_UNIFORMS: number;
    readonly ALIASED_LINE_WIDTH_RANGE: number;
    readonly ALIASED_POINT_SIZE_RANGE: number;
    readonly ALPHA = 0;
    readonly ALPHA_BITS = 0;
    readonly ALWAYS = 0;
    readonly ARRAY_BUFFER = 0;
    readonly ARRAY_BUFFER_BINDING = 0;
    readonly ATTACHED_SHADERS = 0;
    readonly BACK = 0;
    readonly BLEND = 0;
    readonly BLEND_COLOR = 0;
    readonly BLEND_DST_ALPHA = 0;
    readonly BLEND_DST_RGB = 0;
    readonly BLEND_EQUATION = 0;
    readonly BLEND_EQUATION_ALPHA = 0;
    readonly BLEND_EQUATION_RGB = 0;
    readonly BLEND_SRC_ALPHA = 0;
    readonly BLEND_SRC_RGB = 0;
    readonly BLUE_BITS = 0;
    readonly BOOL = 0;
    readonly BOOL_VEC2 = 0;
    readonly BOOL_VEC3 = 0;
    readonly BOOL_VEC4 = 0;
    readonly BROWSER_DEFAULT_WEBGL = 0;
    readonly BUFFER_SIZE = 0;
    readonly BUFFER_USAGE = 0;
    readonly BYTE = 0;
    readonly CCW = 0;
    readonly CLAMP_TO_EDGE = 0;
    readonly COLOR_BUFFER_BIT = 0;
    readonly COLOR_CLEAR_VALUE = 0;
    readonly COLOR_WRITEMASK = 0;
    readonly COMPILE_STATUS = 0;
    readonly COMPRESSED_TEXTURE_FORMATS = 0;
    readonly CONSTANT_ALPHA = 0;
    readonly CONSTANT_COLOR = 0;
    readonly CONTEXT_LOST_WEBGL = 0;
    readonly CULL_FACE = 0;
    readonly CULL_FACE_MODE = 0;
    readonly CURRENT_PROGRAM = 0;
    readonly CURRENT_VERTEX_ATTRIB = 0;
    readonly CW = 0;
    readonly DECR = 0;
    readonly DECR_WRAP = 0;
    readonly DELETE_STATUS = 0;
    readonly DEPTH_ATTACHMENT = 0;
    readonly DEPTH_BITS = 0;
    readonly DEPTH_BUFFER_BIT = 0;
    readonly DEPTH_CLEAR_VALUE = 0;
    readonly DEPTH_COMPONENT = 0;
    readonly DEPTH_COMPONENT16 = 0;
    readonly DEPTH_FUNC = 0;
    readonly DEPTH_RANGE = 0;
    readonly DEPTH_STENCIL = 0;
    readonly DEPTH_STENCIL_ATTACHMENT = 0;
    readonly DEPTH_TEST = 0;
    readonly DEPTH_WRITEMASK = 0;
    readonly DITHER = 0;
    readonly DONT_CARE = 0;
    readonly DST_ALPHA = 0;
    readonly DST_COLOR = 0;
    readonly DYNAMIC_DRAW = 0;
    readonly ELEMENT_ARRAY_BUFFER = 0;
    readonly ELEMENT_ARRAY_BUFFER_BINDING = 0;
    readonly EQUAL = 0;
    readonly FASTEST = 0;
    readonly FLOAT = 0;
    readonly FLOAT_MAT2 = 0;
    readonly FLOAT_MAT3 = 0;
    readonly FLOAT_MAT4 = 0;
    readonly FLOAT_VEC2 = 0;
    readonly FLOAT_VEC3 = 0;
    readonly FLOAT_VEC4 = 0;
    readonly FRAGMENT_SHADER = 0;
    readonly FRAMEBUFFER = 0;
    readonly FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = 0;
    readonly FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = 0;
    readonly FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = 0;
    readonly FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = 0;
    readonly FRAMEBUFFER_BINDING = 0;
    readonly FRAMEBUFFER_COMPLETE = 0;
    readonly FRAMEBUFFER_INCOMPLETE_ATTACHMENT = 0;
    readonly FRAMEBUFFER_INCOMPLETE_DIMENSIONS = 0;
    readonly FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = 0;
    readonly FRAMEBUFFER_UNSUPPORTED = 0;
    readonly FRONT = 0;
    readonly FRONT_AND_BACK = 0;
    readonly FRONT_FACE = 0;
    readonly FUNC_ADD = 0;
    readonly FUNC_REVERSE_SUBTRACT = 0;
    readonly FUNC_SUBTRACT = 0;
    readonly GENERATE_MIPMAP_HINT = 0;
    readonly GEQUAL = 0;
    readonly GREATER = 0;
    readonly GREEN_BITS = 0;
    readonly HIGH_FLOAT = 0;
    readonly HIGH_INT = 0;
    readonly IMPLEMENTATION_COLOR_READ_FORMAT = 0;
    readonly IMPLEMENTATION_COLOR_READ_TYPE = 0;
    readonly INCR = 0;
    readonly INCR_WRAP = 0;
    readonly INT = 0;
    readonly INT_VEC2 = 0;
    readonly INT_VEC3 = 0;
    readonly INT_VEC4 = 0;
    readonly INVALID_ENUM = 0;
    readonly INVALID_FRAMEBUFFER_OPERATION = 0;
    readonly INVALID_OPERATION = 0;
    readonly INVALID_VALUE = 0;
    readonly INVERT = 0;
    readonly KEEP = 0;
    readonly LEQUAL = 0;
    readonly LESS = 0;
    readonly LINEAR = 0;
    readonly LINEAR_MIPMAP_LINEAR = 0;
    readonly LINEAR_MIPMAP_NEAREST = 0;
    readonly LINE_LOOP = 0;
    readonly LINE_STRIP = 0;
    readonly LINE_WIDTH = 0;
    readonly LINES = 0;
    readonly LINK_STATUS = 0;
    readonly LOW_FLOAT = 0;
    readonly LOW_INT = 0;
    readonly LUMINANCE = 0;
    readonly LUMINANCE_ALPHA = 0;
    readonly MAX_COMBINED_TEXTURE_IMAGE_UNITS = 0;
    readonly MAX_CUBE_MAP_TEXTURE_SIZE = 0;
    readonly MAX_FRAGMENT_UNIFORM_VECTORS = 0;
    readonly MAX_RENDERBUFFER_SIZE = 0;
    readonly MAX_TEXTURE_IMAGE_UNITS = 0;
    readonly MAX_TEXTURE_SIZE = 0;
    readonly MAX_VARYING_VECTORS = 0;
    readonly MAX_VERTEX_ATTRIBS = 0;
    readonly MAX_VERTEX_TEXTURE_IMAGE_UNITS = 0;
    readonly MAX_VERTEX_UNIFORM_VECTORS = 0;
    readonly MAX_VIEWPORT_DIMS = 0;
    readonly MEDIUM_FLOAT = 0;
    readonly MEDIUM_INT = 0;
    readonly MIRRORED_REPEAT = 0;
    readonly NEAREST = 0;
    readonly NEAREST_MIPMAP_LINEAR = 0;
    readonly NEAREST_MIPMAP_NEAREST = 0;
    readonly NEVER = 0;
    readonly NICEST = 0;
    readonly NONE = 0;
    readonly NOTEQUAL = 0;
    readonly NO_ERROR = 0;
    readonly ONE = 0;
    readonly ONE_MINUS_CONSTANT_ALPHA = 0;
    readonly ONE_MINUS_CONSTANT_COLOR = 0;
    readonly ONE_MINUS_DST_ALPHA = 0;
    readonly ONE_MINUS_DST_COLOR = 0;
    readonly ONE_MINUS_SRC_ALPHA = 0;
    readonly ONE_MINUS_SRC_COLOR = 0;
    readonly OUT_OF_MEMORY = 0;
    readonly PACK_ALIGNMENT = 0;
    readonly POINTS = 0;
    readonly POLYGON_OFFSET_FACTOR = 0;
    readonly POLYGON_OFFSET_FILL = 0;
    readonly POLYGON_OFFSET_UNITS = 0;
    readonly RED_BITS = 0;
    readonly RENDERBUFFER = 0;
    readonly RENDERBUFFER_ALPHA_SIZE = 0;
    readonly RENDERBUFFER_BINDING = 0;
    readonly RENDERBUFFER_BLUE_SIZE = 0;
    readonly RENDERBUFFER_DEPTH_SIZE = 0;
    readonly RENDERBUFFER_GREEN_SIZE = 0;
    readonly RENDERBUFFER_HEIGHT = 0;
    readonly RENDERBUFFER_INTERNAL_FORMAT = 0;
    readonly RENDERBUFFER_RED_SIZE = 0;
    readonly RENDERBUFFER_STENCIL_SIZE = 0;
    readonly RENDERBUFFER_WIDTH = 0;
    readonly RENDERER = 0;
    readonly REPEAT = 0;
    readonly REPLACE = 0;
    readonly RGB = 0;
    readonly RGB5_A1 = 0;
    readonly RGB565 = 0;
    readonly RGBA = 0;
    readonly RGBA4 = 0;
    readonly SAMPLER_2D = 0;
    readonly SAMPLER_CUBE = 0;
    readonly SAMPLES = 0;
    readonly SAMPLE_ALPHA_TO_COVERAGE = 0;
    readonly SAMPLE_BUFFERS = 0;
    readonly SAMPLE_COVERAGE = 0;
    readonly SAMPLE_COVERAGE_INVERT = 0;
    readonly SAMPLE_COVERAGE_VALUE = 0;
    readonly SCISSOR_BOX = 0;
    readonly SCISSOR_TEST = 0;
    readonly SHADER_TYPE = 0;
    readonly SHADING_LANGUAGE_VERSION = 0;
    readonly SHORT = 0;
    readonly SRC_ALPHA = 0;
    readonly SRC_ALPHA_SATURATE = 0;
    readonly SRC_COLOR = 0;
    readonly STATIC_DRAW = 0;
    readonly STENCIL_ATTACHMENT = 0;
    readonly STENCIL_BACK_FAIL = 0;
    readonly STENCIL_BACK_FUNC = 0;
    readonly STENCIL_BACK_PASS_DEPTH_FAIL = 0;
    readonly STENCIL_BACK_PASS_DEPTH_PASS = 0;
    readonly STENCIL_BACK_REF = 0;
    readonly STENCIL_BACK_VALUE_MASK = 0;
    readonly STENCIL_BACK_WRITEMASK = 0;
    readonly STENCIL_BITS = 0;
    readonly STENCIL_BUFFER_BIT = 0;
    readonly STENCIL_CLEAR_VALUE = 0;
    readonly STENCIL_FAIL = 0;
    readonly STENCIL_FUNC = 0;
    readonly STENCIL_INDEX = 0;
    readonly STENCIL_INDEX8 = 0;
    readonly STENCIL_PASS_DEPTH_FAIL = 0;
    readonly STENCIL_PASS_DEPTH_PASS = 0;
    readonly STENCIL_REF = 0;
    readonly STENCIL_TEST = 0;
    readonly STENCIL_VALUE_MASK = 0;
    readonly STENCIL_WRITEMASK = 0;
    readonly STREAM_DRAW = 0;
    readonly SUBPIXEL_BITS = 0;
    readonly TEXTURE = 0;
    readonly TEXTURE_2D = 0;
    readonly TEXTURE_BINDING_2D = 0;
    readonly TEXTURE_BINDING_CUBE_MAP = 0;
    readonly TEXTURE_CUBE_MAP = 0;
    readonly TEXTURE_CUBE_MAP_NEGATIVE_X = 0;
    readonly TEXTURE_CUBE_MAP_NEGATIVE_Y = 0;
    readonly TEXTURE_CUBE_MAP_NEGATIVE_Z = 0;
    readonly TEXTURE_CUBE_MAP_POSITIVE_X = 0;
    readonly TEXTURE_CUBE_MAP_POSITIVE_Y = 0;
    readonly TEXTURE_CUBE_MAP_POSITIVE_Z = 0;
    readonly TEXTURE_MAG_FILTER = 0;
    readonly TEXTURE_MIN_FILTER = 0;
    readonly TEXTURE_WRAP_S = 0;
    readonly TEXTURE_WRAP_T = 0;
    readonly TEXTURE0 = 0;
    readonly TEXTURE1 = 0;
    readonly TEXTURE2 = 0;
    readonly TEXTURE3 = 0;
    readonly TEXTURE4 = 0;
    readonly TEXTURE5 = 0;
    readonly TEXTURE6 = 0;
    readonly TEXTURE7 = 0;
    readonly TEXTURE8 = 0;
    readonly TEXTURE9 = 0;
    readonly TEXTURE10 = 0;
    readonly TEXTURE11 = 0;
    readonly TEXTURE12 = 0;
    readonly TEXTURE13 = 0;
    readonly TEXTURE14 = 0;
    readonly TEXTURE15 = 0;
    readonly TEXTURE16 = 0;
    readonly TEXTURE17 = 0;
    readonly TEXTURE18 = 0;
    readonly TEXTURE19 = 0;
    readonly TEXTURE20 = 0;
    readonly TEXTURE21 = 0;
    readonly TEXTURE22 = 0;
    readonly TEXTURE23 = 0;
    readonly TEXTURE24 = 0;
    readonly TEXTURE25 = 0;
    readonly TEXTURE26 = 0;
    readonly TEXTURE27 = 0;
    readonly TEXTURE28 = 0;
    readonly TEXTURE29 = 0;
    readonly TEXTURE30 = 0;
    readonly TEXTURE31 = 0;
    readonly TEXTURE32 = 0;
    readonly TRIANGLE_FAN = 0;
    readonly TRIANGLE_STRIP = 0;
    readonly TRIANGLES = 0;
    readonly UNPACK_ALIGNMENT = 0;
    readonly UNPACK_COLORSPACE_CONVERSION_WEBGL = 0;
    readonly UNPACK_FLIP_Y_WEBGL = 0;
    readonly UNPACK_PREMULTIPLY_ALPHA_WEBGL = 0;
    readonly UNSIGNED_BYTE = 0;
    readonly UNSIGNED_INT = 0;
    readonly UNSIGNED_SHORT = 0;
    readonly UNSIGNED_SHORT_4_4_4_4 = 0;
    readonly UNSIGNED_SHORT_5_5_5_1 = 0;
    readonly UNSIGNED_SHORT_5_6_5 = 0;
    readonly VALIDATE_STATUS = 0;
    readonly VENDOR = 0;
    readonly VERSION = 0;
    readonly VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = 0;
    readonly VERTEX_ATTRIB_ARRAY_ENABLED = 0;
    readonly VERTEX_ATTRIB_ARRAY_NORMALIZED = 0;
    readonly VERTEX_ATTRIB_ARRAY_POINTER = 0;
    readonly VERTEX_ATTRIB_ARRAY_SIZE = 0;
    readonly VERTEX_ATTRIB_ARRAY_STRIDE = 0;
    readonly VERTEX_ATTRIB_ARRAY_TYPE = 0;
    readonly VERTEX_SHADER = 0;
    readonly VIEWPORT = 0;
    readonly ZERO = 0;
    readonly READ_BUFFER: number;
    readonly UNPACK_ROW_LENGTH: number;
    readonly UNPACK_SKIP_ROWS: number;
    readonly UNPACK_SKIP_PIXELS: number;
    readonly PACK_ROW_LENGTH: number;
    readonly PACK_SKIP_ROWS: number;
    readonly PACK_SKIP_PIXELS: number;
    readonly COLOR: number;
    readonly DEPTH: number;
    readonly STENCIL: number;
    readonly RED: number;
    readonly RGB8: number;
    readonly RGBA8: number;
    readonly RGB10_A2: number;
    readonly TEXTURE_BINDING_3D: number;
    readonly UNPACK_SKIP_IMAGES: number;
    readonly UNPACK_IMAGE_HEIGHT: number;
    readonly TEXTURE_3D: number;
    readonly TEXTURE_WRAP_R: number;
    readonly MAX_3D_TEXTURE_SIZE: number;
    readonly UNSIGNED_INT_2_10_10_10_REV: number;
    readonly MAX_ELEMENTS_VERTICES: number;
    readonly MAX_ELEMENTS_INDICES: number;
    readonly TEXTURE_MIN_LOD: number;
    readonly TEXTURE_MAX_LOD: number;
    readonly TEXTURE_BASE_LEVEL: number;
    readonly TEXTURE_MAX_LEVEL: number;
    readonly MIN: number;
    readonly MAX: number;
    readonly DEPTH_COMPONENT24: number;
    readonly MAX_TEXTURE_LOD_BIAS: number;
    readonly TEXTURE_COMPARE_MODE: number;
    readonly TEXTURE_COMPARE_FUNC: number;
    readonly CURRENT_QUERY: number;
    readonly QUERY_RESULT: number;
    readonly QUERY_RESULT_AVAILABLE: number;
    readonly STREAM_READ: number;
    readonly STREAM_COPY: number;
    readonly STATIC_READ: number;
    readonly STATIC_COPY: number;
    readonly DYNAMIC_READ: number;
    readonly DYNAMIC_COPY: number;
    readonly MAX_DRAW_BUFFERS: number;
    readonly DRAW_BUFFER0: number;
    readonly DRAW_BUFFER1: number;
    readonly DRAW_BUFFER2: number;
    readonly DRAW_BUFFER3: number;
    readonly DRAW_BUFFER4: number;
    readonly DRAW_BUFFER5: number;
    readonly DRAW_BUFFER6: number;
    readonly DRAW_BUFFER7: number;
    readonly DRAW_BUFFER8: number;
    readonly DRAW_BUFFER9: number;
    readonly DRAW_BUFFER10: number;
    readonly DRAW_BUFFER11: number;
    readonly DRAW_BUFFER12: number;
    readonly DRAW_BUFFER13: number;
    readonly DRAW_BUFFER14: number;
    readonly DRAW_BUFFER15: number;
    readonly MAX_FRAGMENT_UNIFORM_COMPONENTS: number;
    readonly MAX_VERTEX_UNIFORM_COMPONENTS: number;
    readonly SAMPLER_3D: number;
    readonly SAMPLER_2D_SHADOW: number;
    readonly FRAGMENT_SHADER_DERIVATIVE_HINT: number;
    readonly PIXEL_PACK_BUFFER: number;
    readonly PIXEL_UNPACK_BUFFER: number;
    readonly PIXEL_PACK_BUFFER_BINDING: number;
    readonly PIXEL_UNPACK_BUFFER_BINDING: number;
    readonly FLOAT_MAT2x3: number;
    readonly FLOAT_MAT2x4: number;
    readonly FLOAT_MAT3x2: number;
    readonly FLOAT_MAT3x4: number;
    readonly FLOAT_MAT4x2: number;
    readonly FLOAT_MAT4x3: number;
    readonly SRGB: number;
    readonly SRGB8: number;
    readonly SRGB8_ALPHA8: number;
    readonly COMPARE_REF_TO_TEXTURE: number;
    readonly RGBA32F: number;
    readonly RGB32F: number;
    readonly RGBA16F: number;
    readonly RGB16F: number;
    readonly VERTEX_ATTRIB_ARRAY_INTEGER: number;
    readonly MAX_ARRAY_TEXTURE_LAYERS: number;
    readonly MIN_PROGRAM_TEXEL_OFFSET: number;
    readonly MAX_PROGRAM_TEXEL_OFFSET: number;
    readonly MAX_VARYING_COMPONENTS: number;
    readonly TEXTURE_2D_ARRAY: number;
    readonly TEXTURE_BINDING_2D_ARRAY: number;
    readonly R11F_G11F_B10F: number;
    readonly UNSIGNED_INT_10F_11F_11F_REV: number;
    readonly RGB9_E5: number;
    readonly UNSIGNED_INT_5_9_9_9_REV: number;
    readonly TRANSFORM_FEEDBACK_BUFFER_MODE: number;
    readonly MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS: number;
    readonly TRANSFORM_FEEDBACK_VARYINGS: number;
    readonly TRANSFORM_FEEDBACK_BUFFER_START: number;
    readonly TRANSFORM_FEEDBACK_BUFFER_SIZE: number;
    readonly TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN: number;
    readonly RASTERIZER_DISCARD: number;
    readonly MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS: number;
    readonly MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS: number;
    readonly INTERLEAVED_ATTRIBS: number;
    readonly SEPARATE_ATTRIBS: number;
    readonly TRANSFORM_FEEDBACK_BUFFER: number;
    readonly TRANSFORM_FEEDBACK_BUFFER_BINDING: number;
    readonly RGBA32UI: number;
    readonly RGB32UI: number;
    readonly RGBA16UI: number;
    readonly RGB16UI: number;
    readonly RGBA8UI: number;
    readonly RGB8UI: number;
    readonly RGBA32I: number;
    readonly RGB32I: number;
    readonly RGBA16I: number;
    readonly RGB16I: number;
    readonly RGBA8I: number;
    readonly RGB8I: number;
    readonly RED_INTEGER: number;
    readonly RGB_INTEGER: number;
    readonly RGBA_INTEGER: number;
    readonly SAMPLER_2D_ARRAY: number;
    readonly SAMPLER_2D_ARRAY_SHADOW: number;
    readonly SAMPLER_CUBE_SHADOW: number;
    readonly UNSIGNED_INT_VEC2: number;
    readonly UNSIGNED_INT_VEC3: number;
    readonly UNSIGNED_INT_VEC4: number;
    readonly INT_SAMPLER_2D: number;
    readonly INT_SAMPLER_3D: number;
    readonly INT_SAMPLER_CUBE: number;
    readonly INT_SAMPLER_2D_ARRAY: number;
    readonly UNSIGNED_INT_SAMPLER_2D: number;
    readonly UNSIGNED_INT_SAMPLER_3D: number;
    readonly UNSIGNED_INT_SAMPLER_CUBE: number;
    readonly UNSIGNED_INT_SAMPLER_2D_ARRAY: number;
    readonly DEPTH_COMPONENT32F: number;
    readonly DEPTH32F_STENCIL8: number;
    readonly FLOAT_32_UNSIGNED_INT_24_8_REV: number;
    readonly FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING: number;
    readonly FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE: number;
    readonly FRAMEBUFFER_ATTACHMENT_RED_SIZE: number;
    readonly FRAMEBUFFER_ATTACHMENT_GREEN_SIZE: number;
    readonly FRAMEBUFFER_ATTACHMENT_BLUE_SIZE: number;
    readonly FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE: number;
    readonly FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE: number;
    readonly FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE: number;
    readonly FRAMEBUFFER_DEFAULT: number;
    readonly UNSIGNED_INT_24_8: number;
    readonly DEPTH24_STENCIL8: number;
    readonly UNSIGNED_NORMALIZED: number;
    readonly DRAW_FRAMEBUFFER_BINDING: number;
    readonly READ_FRAMEBUFFER: number;
    readonly DRAW_FRAMEBUFFER: number;
    readonly READ_FRAMEBUFFER_BINDING: number;
    readonly RENDERBUFFER_SAMPLES: number;
    readonly FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER: number;
    readonly MAX_COLOR_ATTACHMENTS: number;
    readonly COLOR_ATTACHMENT0: number;
    readonly COLOR_ATTACHMENT1: number;
    readonly COLOR_ATTACHMENT2: number;
    readonly COLOR_ATTACHMENT3: number;
    readonly COLOR_ATTACHMENT4: number;
    readonly COLOR_ATTACHMENT5: number;
    readonly COLOR_ATTACHMENT6: number;
    readonly COLOR_ATTACHMENT7: number;
    readonly COLOR_ATTACHMENT8: number;
    readonly COLOR_ATTACHMENT9: number;
    readonly COLOR_ATTACHMENT10: number;
    readonly COLOR_ATTACHMENT11: number;
    readonly COLOR_ATTACHMENT12: number;
    readonly COLOR_ATTACHMENT13: number;
    readonly COLOR_ATTACHMENT14: number;
    readonly COLOR_ATTACHMENT15: number;
    readonly FRAMEBUFFER_INCOMPLETE_MULTISAMPLE: number;
    readonly MAX_SAMPLES: number;
    readonly HALF_FLOAT: number;
    readonly RG: number;
    readonly RG_INTEGER: number;
    readonly R8: number;
    readonly RG8: number;
    readonly R16F: number;
    readonly R32F: number;
    readonly RG16F: number;
    readonly RG32F: number;
    readonly R8I: number;
    readonly R8UI: number;
    readonly R16I: number;
    readonly R16UI: number;
    readonly R32I: number;
    readonly R32UI: number;
    readonly RG8I: number;
    readonly RG8UI: number;
    readonly RG16I: number;
    readonly RG16UI: number;
    readonly RG32I: number;
    readonly RG32UI: number;
    readonly VERTEX_ARRAY_BINDING: number;
    readonly R8_SNORM: number;
    readonly RG8_SNORM: number;
    readonly RGB8_SNORM: number;
    readonly RGBA8_SNORM: number;
    readonly SIGNED_NORMALIZED: number;
    readonly COPY_READ_BUFFER: number;
    readonly COPY_WRITE_BUFFER: number;
    readonly COPY_READ_BUFFER_BINDING: number;
    readonly COPY_WRITE_BUFFER_BINDING: number;
    readonly UNIFORM_BUFFER: number;
    readonly UNIFORM_BUFFER_BINDING: number;
    readonly UNIFORM_BUFFER_START: number;
    readonly UNIFORM_BUFFER_SIZE: number;
    readonly MAX_VERTEX_UNIFORM_BLOCKS: number;
    readonly MAX_FRAGMENT_UNIFORM_BLOCKS: number;
    readonly MAX_COMBINED_UNIFORM_BLOCKS: number;
    readonly MAX_UNIFORM_BUFFER_BINDINGS: number;
    readonly MAX_UNIFORM_BLOCK_SIZE: number;
    readonly MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS: number;
    readonly MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS: number;
    readonly UNIFORM_BUFFER_OFFSET_ALIGNMENT: number;
    readonly ACTIVE_UNIFORM_BLOCKS: number;
    readonly UNIFORM_TYPE: number;
    readonly UNIFORM_SIZE: number;
    readonly UNIFORM_BLOCK_INDEX: number;
    readonly UNIFORM_OFFSET: number;
    readonly UNIFORM_ARRAY_STRIDE: number;
    readonly UNIFORM_MATRIX_STRIDE: number;
    readonly UNIFORM_IS_ROW_MAJOR: number;
    readonly UNIFORM_BLOCK_BINDING: number;
    readonly UNIFORM_BLOCK_DATA_SIZE: number;
    readonly UNIFORM_BLOCK_ACTIVE_UNIFORMS: number;
    readonly UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES: number;
    readonly UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER: number;
    readonly UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER: number;
    readonly INVALID_INDEX: number;
    readonly MAX_VERTEX_OUTPUT_COMPONENTS: number;
    readonly MAX_FRAGMENT_INPUT_COMPONENTS: number;
    readonly MAX_SERVER_WAIT_TIMEOUT: number;
    readonly OBJECT_TYPE: number;
    readonly SYNC_CONDITION: number;
    readonly SYNC_STATUS: number;
    readonly SYNC_FLAGS: number;
    readonly SYNC_FENCE: number;
    readonly SYNC_GPU_COMMANDS_COMPLETE: number;
    readonly UNSIGNALED: number;
    readonly SIGNALED: number;
    readonly ALREADY_SIGNALED: number;
    readonly TIMEOUT_EXPIRED: number;
    readonly CONDITION_SATISFIED: number;
    readonly WAIT_FAILED: number;
    readonly SYNC_FLUSH_COMMANDS_BIT: number;
    readonly VERTEX_ATTRIB_ARRAY_DIVISOR: number;
    readonly ANY_SAMPLES_PASSED: number;
    readonly ANY_SAMPLES_PASSED_CONSERVATIVE: number;
    readonly SAMPLER_BINDING: number;
    readonly RGB10_A2UI: number;
    readonly INT_2_10_10_10_REV: number;
    readonly TRANSFORM_FEEDBACK: number;
    readonly TRANSFORM_FEEDBACK_PAUSED: number;
    readonly TRANSFORM_FEEDBACK_ACTIVE: number;
    readonly TRANSFORM_FEEDBACK_BINDING: number;
    readonly TEXTURE_IMMUTABLE_FORMAT: number;
    readonly MAX_ELEMENT_INDEX: number;
    readonly TEXTURE_IMMUTABLE_LEVELS: number;
    readonly TIMEOUT_IGNORED: number;
    readonly MAX_CLIENT_WAIT_TIMEOUT_WEBGL: number;
    canvas: HTMLCanvasElement;
    drawingBufferWidth: number;
    drawingBufferHeight: number;
    constructor(canvas: CanvasMock);
    activeTexture(): void;
    attachShader(): void;
    beginQuery(): void;
    beginTransformFeedback(): void;
    bindAttribLocation(): void;
    bindBuffer(): void;
    bindBufferBase(): void;
    bindBufferRange(): void;
    bindFramebuffer(): void;
    bindRenderbuffer(): void;
    bindSampler(): void;
    bindTexture(): void;
    bindTransformFeedback(): void;
    bindVertexArray(): void;
    blendColor(): void;
    blendEquation(): void;
    blendEquationSeparate(): void;
    blendFunc(): void;
    blendFuncSeparate(): void;
    blitFramebuffer(): void;
    bufferData(): void;
    bufferSubData(): void;
    checkFramebufferStatus(): number;
    clear(): void;
    clearBufferfi(): void;
    clearBufferfv(): void;
    clearBufferiv(): void;
    clearBufferuiv(): void;
    clearColor(): void;
    clearDepth(): void;
    clearStencil(): void;
    clientWaitSync(): number;
    colorMask(): void;
    compileShader(): void;
    compressedTexImage2D(): void;
    compressedTexImage3D(): void;
    compressedTexSubImage2D(): void;
    compressedTexSubImage3D(): void;
    copyBufferSubData(): void;
    copyTexImage2D(): void;
    copyTexSubImage2D(): void;
    copyTexSubImage3D(): void;
    createBuffer(): WebGLBuffer | null;
    createFramebuffer(): WebGLFramebuffer | null;
    createProgram(): WebGLProgram | null;
    createRenderbuffer(): WebGLRenderbuffer;
    createSampler(): WebGLSampler | null;
    createShader(): WebGLShader | null;
    createTexture(): WebGLTexture | null;
    createTransformFeedback(): WebGLTransformFeedback | null;
    createQuery(): WebGLQuery | null;
    createVertexArray(): WebGLVertexArrayObject | null;
    cullFace(): void;
    deleteBuffer(): void;
    deleteFramebuffer(): void;
    deleteProgram(): void;
    deleteRenderbuffer(): void;
    deleteSampler(): void;
    deleteShader(): void;
    deleteTexture(): void;
    deleteTransformFeedback(): void;
    deleteQuery(): void;
    deleteSync(): void;
    deleteVertexArray(): void;
    depthFunc(): void;
    depthMask(): void;
    depthRange(): void;
    detachShader(): void;
    disable(): void;
    disableVertexAttribArray(): void;
    drawArrays(): void;
    drawArraysInstanced(): void;
    drawBuffers(): void;
    drawElements(): void;
    drawElementsInstanced(): void;
    drawRangeElements(): void;
    enable(): void;
    enableVertexAttribArray(): void;
    endQuery(): void;
    endTransformFeedback(): void;
    fenceSync(): WebGLSync | null;
    finish(): void;
    flush(): void;
    framebufferRenderbuffer(): void;
    framebufferTexture2D(): void;
    framebufferTextureLayer(): void;
    frontFace(): void;
    generateMipmap(): void;
    getActiveAttrib(): WebGLActiveInfo | null;
    getActiveUniform(): WebGLActiveInfo | null;
    getActiveUniforms(): WebGLActiveInfo | null;
    getActiveUniformBlockName(): string | null;
    getActiveUniformBlockParameter(): WebGLActiveInfo | null;
    getAttachedShaders(): WebGLShader[] | null;
    getAttribLocation(): number;
    getBufferParameter(): unknown;
    getBufferSubData(): unknown;
    getContextAttributes(): WebGLContextAttributes;
    getError(): number;
    getExtension(): null;
    getFragDataLocation(): number;
    getFramebufferAttachmentParameter(): unknown;
    getIndexedParameter(): unknown;
    getInternalformatParameter(): unknown;
    getParameter(): unknown;
    getProgramParameter(): unknown;
    getProgramInfoLog(): string | null;
    getRenderbufferParameter(): unknown;
    getSamplerParameter(): unknown;
    getShaderParameter(): unknown;
    getShaderInfoLog(): string | null;
    getShaderPrecisionFormat(): WebGLShaderPrecisionFormat | null;
    getShaderSource(): string | null;
    getSupportedExtensions(): string[];
    getSyncParameter(): unknown;
    getTexParameter(): unknown;
    getTransformFeedbackVarying(): WebGLActiveInfo | null;
    getQuery(): WebGLQuery | null;
    getQueryParameter(): unknown;
    getUniform(): unknown;
    getUniformBlockIndex(): number;
    getUniformIndices(): number[] | null;
    getUniformLocation(): WebGLUniformLocation | null;
    getVertexAttrib(): unknown;
    getVertexAttribOffset(): number;
    hint(): unknown;
    invalidateFramebuffer(): void;
    invalidateSubFramebuffer(): void;
    isBuffer(): boolean;
    isContextLost(): boolean;
    isEnabled(): boolean;
    isFramebuffer(): boolean;
    isProgram(): boolean;
    isRenderbuffer(): boolean;
    isSampler(): boolean;
    isShader(): boolean;
    isSync(): boolean;
    isVertexArray(): boolean;
    isTexture(): boolean;
    isTransformFeedback(): boolean;
    isQuery(): boolean;
    lineWidth(): void;
    linkProgram(): void;
    pauseTransformFeedback(): void;
    pixelStorei(): void;
    polygonOffset(): void;
    readBuffer(): void;
    readPixels(): void;
    renderbufferStorage(): void;
    renderbufferStorageMultisample(): void;
    resumeTransformFeedback(): void;
    sampleCoverage(): void;
    samplerParameteri(): void;
    samplerParameterf(): void;
    scissor(): void;
    shaderSource(): void;
    stencilFunc(): void;
    stencilFuncSeparate(): void;
    stencilMask(): void;
    stencilMaskSeparate(): void;
    stencilOp(): void;
    stencilOpSeparate(): void;
    texParameterf(): void;
    texParameteri(): void;
    texImage2D(): void;
    texImage3D(): void;
    texStorage2D(): void;
    texStorage3D(): void;
    texSubImage2D(): void;
    texSubImage3D(): void;
    transformFeedbackVaryings(): void;
    uniformBlockBinding(): void;
    uniform1f(): void;
    uniform1fv(): void;
    uniform1i(): void;
    uniform1iv(): void;
    uniform1ui(): void;
    uniform1uiv(): void;
    uniform2f(): void;
    uniform2fv(): void;
    uniform2i(): void;
    uniform2iv(): void;
    uniform2ui(): void;
    uniform2uiv(): void;
    uniform3f(): void;
    uniform3fv(): void;
    uniform3i(): void;
    uniform3iv(): void;
    uniform3ui(): void;
    uniform3uiv(): void;
    uniform4f(): void;
    uniform4fv(): void;
    uniform4i(): void;
    uniform4iv(): void;
    uniform4ui(): void;
    uniform4uiv(): void;
    uniformMatrix2fv(): void;
    uniformMatrix2x3fv(): void;
    uniformMatrix2x4fv(): void;
    uniformMatrix3fv(): void;
    uniformMatrix3x2fv(): void;
    uniformMatrix3x4fv(): void;
    uniformMatrix4fv(): void;
    uniformMatrix4x2fv(): void;
    uniformMatrix4x3fv(): void;
    useProgram(): void;
    validateProgram(): void;
    vertexAttrib1f(): void;
    vertexAttrib1fv(): void;
    vertexAttrib2f(): void;
    vertexAttrib2fv(): void;
    vertexAttrib3f(): void;
    vertexAttrib3fv(): void;
    vertexAttrib4f(): void;
    vertexAttrib4fv(): void;
    vertexAttribDivisor(): void;
    vertexAttribPointer(): void;
    vertexAttribI4i(): void;
    vertexAttribI4iv(): void;
    vertexAttribI4ui(): void;
    vertexAttribI4uiv(): void;
    vertexAttribIPointer(): void;
    viewport(): void;
    waitSync(): void;
}
//# sourceMappingURL=webgl-mock.d.ts.map