export declare function isTrue(got: any, fmt?: (got: any) => string): void;
export declare function isFalse(got: any, fmt?: (got: any) => string): void;
export declare function nonNull(got: any, fmt?: (got: any) => string): void;
export declare function nonEmpty<T>(got: string | T[], fmt?: (got: string | T[]) => string): void;
export declare function equal<T>(got: T, expected: T, fmt?: (got: T, expected: T) => string): void;
export declare function oneOf<T>(got: T, expected: T[], fmt?: (got: T, expected: T[]) => string): void;
export declare function gt(got: number, low: number, fmt?: (got: number, low: number) => string): void;
export declare function gte(got: number, low: number, fmt?: (got: number, low: number) => string): void;
export declare function rangeInclusive(got: number, low: number, high: number, fmt?: (got: number, low: number, high: number) => string): void;
export declare function never(got: never, fmt?: (p: any) => string): never;
//# sourceMappingURL=assert.d.ts.map