export declare function isTrue(got: unknown, fmt?: (got: unknown) => string): got is true;
export declare function isFalse(got: unknown, fmt?: (got: unknown) => string): got is false;
export declare function isArray(got: unknown, fmt?: (got: unknown) => string): got is unknown[];
export declare function nonNull(got: unknown, fmt?: (got: unknown) => string): boolean;
export declare function nonEmpty<T>(got: string | T[], fmt?: (got: string | T[]) => string): boolean;
export declare function equal<T>(got: T, expected: T, fmt?: (got: T, expected: T) => string): boolean;
export declare function oneOf<T>(got: T, expected: T[], fmt?: (got: T, expected: T[]) => string): boolean;
export declare function gt(got: number, low: number, fmt?: (got: number, low: number) => string): boolean;
export declare function gte(got: number, low: number, fmt?: (got: number, low: number) => string): boolean;
export declare function rangeInclusive(got: number, low: number, high: number, fmt?: (got: number, low: number, high: number) => string): boolean;
export declare function unreachable(got: never, fmt?: (p: unknown) => string): never;
//# sourceMappingURL=assert.d.ts.map